import { useEffect, useRef, useState, type PointerEvent as ReactPointerEvent } from 'react'
import { BoxSelect, Cloud, Copy, Download, Eye, FileUp, Maximize2, Grid3X3, Link2, Monitor, Network, Plus, Redo2, Router, Server, Shield, Trash2, Undo2, Wifi, ZoomIn, ZoomOut } from 'lucide-react'
import { diagramSchema, parseImportedJson } from '../lib/schemas'
import { downloadText } from '../lib/files'
import { nowIso, uid, type DeviceType, type Diagram, type DiagramLink, type DiagramNode } from '../types'
import { useAppData } from '../state/DataContext'
import { EmptyState, Field, PageIntro } from '../components/UI'

const nodeTypes: Array<{ type: DeviceType; label: string; icon: typeof Router }> = [
  {type:'router',label:'Router',icon:Router},{type:'l2-switch',label:'L2 switch',icon:Network},{type:'l3-switch',label:'L3 switch',icon:Network},{type:'firewall',label:'Firewall',icon:Shield},{type:'server',label:'Server',icon:Server},{type:'access-point',label:'Wireless AP',icon:Wifi},{type:'cloud',label:'Cloud / Internet',icon:Cloud},{type:'endpoint',label:'Endpoint',icon:Monitor},{type:'device',label:'Generic device',icon:BoxSelect},{type:'annotation',label:'Text annotation',icon:BoxSelect},{type:'group',label:'Site boundary',icon:BoxSelect}
]
const emptyDiagram = (name = 'Untitled diagram'): Diagram => { const now=nowIso(); return {id:uid('diagram'),name,nodes:[],links:[],grid:true,snap:true,createdAt:now,updatedAt:now} }
const exampleDiagram = (): Diagram => { const diagram=emptyDiagram('Branch edge example'); diagram.nodes=[
  {id:uid('node'),type:'cloud',x:70,y:180,name:'Internet',color:'#2387c9'},{id:uid('node'),type:'firewall',x:260,y:180,name:'Edge firewall',managementIp:'10.44.99.2',color:'#df7b17'},{id:uid('node'),type:'l3-switch',x:470,y:180,name:'Core switch',managementIp:'10.44.99.3',color:'#8b5cf6'},{id:uid('node'),type:'access-point',x:670,y:90,name:'Office AP',managementIp:'10.44.99.20',color:'#15976f'},{id:uid('node'),type:'server',x:670,y:280,name:'Local services',managementIp:'10.44.99.30',color:'#4d75c7'}
  ]; diagram.links=[{id:uid('link'),source:diagram.nodes[0]!.id,target:diagram.nodes[1]!.id,speed:'1 Gbps',lineStyle:'solid'},{id:uid('link'),source:diagram.nodes[1]!.id,target:diagram.nodes[2]!.id,speed:'10 Gbps',vlanLabel:'trunk',lineStyle:'solid'},{id:uid('link'),source:diagram.nodes[2]!.id,target:diagram.nodes[3]!.id,speed:'1 Gbps',vlanLabel:'VLAN 10',lineStyle:'dashed'},{id:uid('link'),source:diagram.nodes[2]!.id,target:diagram.nodes[4]!.id,speed:'10 Gbps',vlanLabel:'VLAN 99',lineStyle:'solid'}]; return diagram }

export default function DiagramPage() {
  const {data,setData,notify}=useAppData()
  const fileRef=useRef<HTMLInputElement>(null), canvasRef=useRef<SVGSVGElement>(null)
  const active=data.diagrams.find((item)=>item.id===data.preferences.activeDiagramId)??data.diagrams[0]
  const [selected,setSelected]=useState<string[]>([]), [selectedLink,setSelectedLink]=useState(''), [connectFrom,setConnectFrom]=useState('')
  const [preview,setPreview]=useState(false), [view,setView]=useState({x:0,y:0,zoom:1}), [history,setHistory]=useState<Diagram[]>([]), [future,setFuture]=useState<Diagram[]>([])
  const drag=useRef<{kind:'nodes'|'pan';startX:number;startY:number;positions?:Record<string,{x:number;y:number}>;view?:{x:number;y:number}}|null>(null)
  const selectedNode=active?.nodes.find((node)=>node.id===selected[0]), selectedEdge=active?.links.find((link)=>link.id===selectedLink)
  const vlanOptions=data.plans.flatMap((plan)=>plan.vlans.map((vlan)=>({...vlan,planName:plan.name})))
  const commit=(transform:(diagram:Diagram)=>Diagram,record=true)=>{if(!active)return;const next={...transform(active),updatedAt:nowIso()};if(record){setHistory((items)=>[...items.slice(-49),active]);setFuture([])}setData((current)=>({...current,diagrams:current.diagrams.map((item)=>item.id===active.id?next:item)}))}
  const createDiagram=(diagram=emptyDiagram(`Diagram ${data.diagrams.length+1}`))=>{setData((current)=>({...current,diagrams:[...current.diagrams,diagram],preferences:{...current.preferences,activeDiagramId:diagram.id}}));setSelected([]);setSelectedLink('');setHistory([]);setFuture([]);notify('Diagram created')}
  const addNode=(type:DeviceType)=>{if(!active||preview)return;const meta=nodeTypes.find((item)=>item.type===type)!;const count=active.nodes.filter((node)=>node.type===type).length+1;const node:DiagramNode={id:uid('node'),type,x:Math.round((180-view.x)/view.zoom)+count*14,y:Math.round((120-view.y)/view.zoom)+count*14,name:`${meta.label} ${count}`,color:type==='firewall'?'#df7b17':type==='l3-switch'?'#8b5cf6':'#2387c9',width:type==='group'?300:undefined,height:type==='group'?180:undefined};commit((diagram)=>({...diagram,nodes:[...diagram.nodes,node]}));setSelected([node.id]);setSelectedLink('')}
  const removeSelected=()=>{if(!active||preview)return;if(selected.length){const ids=new Set(selected);commit((diagram)=>({...diagram,nodes:diagram.nodes.filter((node)=>!ids.has(node.id)),links:diagram.links.filter((link)=>!ids.has(link.source)&&!ids.has(link.target))}));setSelected([])}else if(selectedLink){commit((diagram)=>({...diagram,links:diagram.links.filter((link)=>link.id!==selectedLink)}));setSelectedLink('')}}
  const duplicateSelected=()=>{if(!active||!selected.length||preview)return;const ids=new Set(selected),copies=active.nodes.filter((node)=>ids.has(node.id)).map((node)=>({...node,id:uid('node'),x:node.x+30,y:node.y+30,name:`${node.name} copy`}));commit((diagram)=>({...diagram,nodes:[...diagram.nodes,...copies]}));setSelected(copies.map((node)=>node.id))}
  const undo=()=>{const prior=history.at(-1);if(!active||!prior)return;setFuture((items)=>[active,...items]);setHistory((items)=>items.slice(0,-1));setData((current)=>({...current,diagrams:current.diagrams.map((item)=>item.id===active.id?prior:item)}))}
  const redo=()=>{const next=future[0];if(!active||!next)return;setHistory((items)=>[...items,active]);setFuture((items)=>items.slice(1));setData((current)=>({...current,diagrams:current.diagrams.map((item)=>item.id===active.id?next:item)}))}
  const nodePointerDown=(event:ReactPointerEvent, node:DiagramNode)=>{if(preview)return;event.stopPropagation();if(connectFrom){if(connectFrom!==node.id){commit((diagram)=>({...diagram,links:[...diagram.links,{id:uid('link'),source:connectFrom,target:node.id,lineStyle:'solid'}]}));setConnectFrom('');notify('Connection added')}return}const next=event.shiftKey?(selected.includes(node.id)?selected.filter((id)=>id!==node.id):[...selected,node.id]):selected.includes(node.id)?selected:[node.id];setSelected(next);setSelectedLink('');const positions=Object.fromEntries(active!.nodes.filter((item)=>next.includes(item.id)).map((item)=>[item.id,{x:item.x,y:item.y}]));drag.current={kind:'nodes',startX:event.clientX,startY:event.clientY,positions};event.currentTarget.setPointerCapture(event.pointerId)}
  const canvasPointerDown=(event:ReactPointerEvent<SVGSVGElement>)=>{if(event.target!==event.currentTarget)return;setSelected([]);setSelectedLink('');if(!preview)drag.current={kind:'pan',startX:event.clientX,startY:event.clientY,view:{x:view.x,y:view.y}}}
  const pointerMove=(event:ReactPointerEvent<SVGSVGElement>)=>{if(!drag.current||!active)return;if(drag.current.kind==='pan'&&drag.current.view){setView((current)=>({...current,x:drag.current!.view!.x+event.clientX-drag.current!.startX,y:drag.current!.view!.y+event.clientY-drag.current!.startY}))}else if(drag.current.positions){const dx=(event.clientX-drag.current.startX)/view.zoom,dy=(event.clientY-drag.current.startY)/view.zoom;commit((diagram)=>({...diagram,nodes:diagram.nodes.map((node)=>{const origin=drag.current!.positions![node.id];if(!origin)return node;let x=origin.x+dx,y=origin.y+dy;if(diagram.snap){x=Math.round(x/20)*20;y=Math.round(y/20)*20}return{...node,x,y}})}),false)}}
  const pointerUp=()=>{if(drag.current?.kind==='nodes'&&active){setHistory((items)=>[...items.slice(-49),{...active,nodes:active.nodes.map((node)=>{const origin=drag.current?.positions?.[node.id];return origin?{...node,...origin}:node})}]);setFuture([])}drag.current=null}
  const fit=()=>{if(!active?.nodes.length){setView({x:0,y:0,zoom:1});return}const xs=active.nodes.map((node)=>node.x),ys=active.nodes.map((node)=>node.y);const box=canvasRef.current?.getBoundingClientRect();if(!box)return;const width=Math.max(...xs)-Math.min(...xs)+180,height=Math.max(...ys)-Math.min(...ys)+130;const zoom=Math.min(1.5,Math.max(.25,Math.min(box.width/width,box.height/height)));setView({zoom,x:box.width/2-((Math.min(...xs)+Math.max(...xs)+120)/2)*zoom,y:box.height/2-((Math.min(...ys)+Math.max(...ys)+60)/2)*zoom})}
  const updateNode=(patch:Partial<DiagramNode>)=>selectedNode&&commit((diagram)=>({...diagram,nodes:diagram.nodes.map((node)=>node.id===selectedNode.id?{...node,...patch}:node)}))
  const updateLink=(patch:Partial<DiagramLink>)=>selectedEdge&&commit((diagram)=>({...diagram,links:diagram.links.map((link)=>link.id===selectedEdge.id?{...link,...patch}:link)}))
  useEffect(()=>{const key=(event:KeyboardEvent)=>{const target=event.target as HTMLElement;if(target.matches('input,textarea,select,[contenteditable="true"]'))return;if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='z'){event.preventDefault();if(event.shiftKey)redo();else undo()}else if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='d'){event.preventDefault();duplicateSelected()}else if(event.key==='Delete'||event.key==='Backspace'){event.preventDefault();removeSelected()}else if(event.key==='Escape')setConnectFrom('')};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)})
  const exportJson=()=>{if(active){downloadText(`${active.name.replace(/[^a-z0-9]+/gi,'-').toLowerCase()}.diagram.json`,JSON.stringify(active,null,2));notify('Diagram JSON exported')}}
  const importJson=async(file?:File)=>{if(!file)return;try{const imported=parseImportedJson(await file.text(),diagramSchema);createDiagram({...imported,id:uid('diagram'),name:`${imported.name} (imported)`,updatedAt:nowIso()})}catch(error){notify(error instanceof Error?error.message:'Import failed')}finally{if(fileRef.current)fileRef.current.value=''}}
  const serializeSvg=()=>{const svg=canvasRef.current;if(!svg)return null;const clone=svg.cloneNode(true) as SVGSVGElement;clone.setAttribute('xmlns','http://www.w3.org/2000/svg');clone.setAttribute('width',String(svg.clientWidth));clone.setAttribute('height',String(svg.clientHeight));clone.querySelectorAll('.canvas-controls').forEach((item)=>item.remove());return new XMLSerializer().serializeToString(clone)}
  const exportSvg=()=>{const text=serializeSvg();if(text){downloadText(`${active?.name??'diagram'}.svg`,text,'image/svg+xml');notify('SVG exported')}}
  const exportPng=()=>{const text=serializeSvg(),svg=canvasRef.current;if(!text||!svg)return;const url=URL.createObjectURL(new Blob([text],{type:'image/svg+xml'}));const image=new Image();image.onload=()=>{const canvas=document.createElement('canvas');canvas.width=Math.max(1,svg.clientWidth*2);canvas.height=Math.max(1,svg.clientHeight*2);const context=canvas.getContext('2d');if(!context)return;context.scale(2,2);context.fillStyle=getComputedStyle(document.documentElement).getPropertyValue('--surface-2');context.fillRect(0,0,svg.clientWidth,svg.clientHeight);context.drawImage(image,0,0);canvas.toBlob((blob)=>{if(blob){const png=URL.createObjectURL(blob);const a=document.createElement('a');a.href=png;a.download=`${active?.name??'diagram'}.png`;a.click();URL.revokeObjectURL(png);notify('PNG exported')}},'image/png');URL.revokeObjectURL(url)};image.src=url}
  if(!active)return <><PageIntro eyebrow="Topology planning" title="Network Diagram Scratchpad" description="Sketch a local topology with devices, annotated links, pan, zoom, undo, and export."/><section className="panel"><EmptyState icon={<Network/>} title="No diagrams yet" action={<div className="form-actions"><button className="primary" onClick={()=>createDiagram()}><Plus size={15}/>Create blank diagram</button><button onClick={()=>createDiagram(exampleDiagram())}>Load example topology</button></div>}>Start empty or intentionally load a small branch-edge example.</EmptyState></section></>
  const nodeMap=new Map(active.nodes.map((node)=>[node.id,node]))
  return <>
    <PageIntro eyebrow="Topology planning" title="Network Diagram Scratchpad" description="Create and annotate local topology sketches. Changes autosave to the selected diagram." actions={<><select aria-label="Select diagram" value={active.id} onChange={(event)=>setData((current)=>({...current,preferences:{...current.preferences,activeDiagramId:event.target.value}}))}>{data.diagrams.map((diagram)=><option value={diagram.id} key={diagram.id}>{diagram.name}</option>)}</select><button onClick={()=>createDiagram()}><Plus size={15}/>New</button></>}/>
    <div className="diagram-toolbar"><button className="small" disabled={!history.length} onClick={undo}><Undo2 size={14}/>Undo</button><button className="small" disabled={!future.length} onClick={redo}><Redo2 size={14}/>Redo</button><button className="small" onClick={duplicateSelected}><Copy size={14}/>Duplicate</button><button className="small danger" onClick={removeSelected}><Trash2 size={14}/>Delete</button><button className={`small ${connectFrom?'primary':''}`} onClick={()=>setConnectFrom(selected[0]??'')} disabled={!selected.length}><Link2 size={14}/>{connectFrom?'Select target':'Connect'}</button><button className="small" onClick={fit}><Maximize2 size={14}/>Fit</button><button className="small" onClick={()=>setPreview((value)=>!value)}><Eye size={14}/>{preview?'Exit preview':'Preview'}</button><button className="small" onClick={exportJson}><Download size={14}/>JSON</button><button className="small" onClick={exportSvg}><Download size={14}/>SVG</button><button className="small" onClick={exportPng}><Download size={14}/>PNG</button><button className="small" onClick={()=>fileRef.current?.click()}><FileUp size={14}/>Import</button><input className="sr-only" ref={fileRef} type="file" accept="application/json,.json" onChange={(event)=>void importJson(event.target.files?.[0])}/></div>
    <div className="diagram-layout"><aside className="diagram-palette"><span className="eyebrow" style={{marginBottom:9}}>Add device</span><div className="palette-list">{nodeTypes.map(({type,label,icon:Icon})=><button className="palette-item" key={type} disabled={preview} onClick={()=>addNode(type)}><Icon size={14}/>{label}</button>)}</div><hr style={{border:0,borderTop:'1px solid var(--line)',margin:'14px 0'}}/><label className="check-row"><input type="checkbox" checked={active.grid} onChange={(event)=>commit((diagram)=>({...diagram,grid:event.target.checked}))}/><Grid3X3 size={14}/>Grid</label><label className="check-row" style={{marginTop:9}}><input type="checkbox" checked={active.snap} onChange={(event)=>commit((diagram)=>({...diagram,snap:event.target.checked}))}/>Snap to grid</label><div className="shortcut-list" style={{marginTop:18}}><span>Delete</span><kbd>Del</kbd><span>Duplicate</span><kbd>Ctrl D</kbd><span>Undo</span><kbd>Ctrl Z</kbd><span>Cancel link</span><kbd>Esc</kbd></div></aside>
      <div className="diagram-canvas-wrap" style={{backgroundImage:active.grid?undefined:'none'}}><svg ref={canvasRef} className="diagram-canvas" onPointerDown={canvasPointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp} onWheel={(event)=>{event.preventDefault();setView((current)=>({...current,zoom:Math.min(2.5,Math.max(.25,current.zoom*(event.deltaY<0?1.1:.9)))}))}}><g transform={`translate(${view.x} ${view.y}) scale(${view.zoom})`}>
        {active.links.map((link)=>{const source=nodeMap.get(link.source),target=nodeMap.get(link.target);if(!source||!target)return null;const x1=source.x+60,y1=source.y+30,x2=target.x+60,y2=target.y+30;return <g key={link.id} onPointerDown={(event)=>{if(preview)return;event.stopPropagation();setSelectedLink(link.id);setSelected([])}}><line className={`diagram-link ${selectedLink===link.id?'selected':''}`} x1={x1} y1={y1} x2={x2} y2={y2} stroke={link.color} strokeDasharray={link.lineStyle==='dashed'?'8 5':link.lineStyle==='dotted'?'2 5':undefined}/><text x={(x1+x2)/2} y={(y1+y2)/2-7} textAnchor="middle" fill="var(--muted)" fontSize="9">{[link.speed,link.vlanLabel].filter(Boolean).join(' · ')}</text></g>})}
        {active.nodes.map((node)=>{const group=node.type==='group',annotation=node.type==='annotation';return <g key={node.id} className={`diagram-node ${selected.includes(node.id)?'selected':''}`} transform={`translate(${node.x} ${node.y})`} onPointerDown={(event)=>nodePointerDown(event,node)}><rect width={node.width??120} height={node.height??60} rx={group?8:10} fill={annotation?'transparent':group?'color-mix(in srgb, var(--accent-soft) 24%, transparent)':'var(--surface)'} stroke={node.color??'var(--line-strong)'} strokeDasharray={group?'7 5':undefined}/><text x={group?10:60} y={annotation?22:26} textAnchor={group||annotation?'start':'middle'}>{node.name}</text>{!group&&!annotation&&<text className="node-sub" x="60" y="43" textAnchor="middle">{node.managementIp||nodeTypes.find((item)=>item.type===node.type)?.label}</text>}</g>})}
      </g></svg>{!active.nodes.length&&<div className="diagram-empty">Choose a device type to begin.</div>}<div className="canvas-zoom"><button className="small" aria-label="Zoom out" onClick={()=>setView((current)=>({...current,zoom:Math.max(.25,current.zoom-.15)}))}><ZoomOut/></button><button className="small" onClick={()=>setView((current)=>({...current,zoom:1}))}>{Math.round(view.zoom*100)}%</button><button className="small" aria-label="Zoom in" onClick={()=>setView((current)=>({...current,zoom:Math.min(2.5,current.zoom+.15)}))}><ZoomIn/></button></div></div>
      {!preview&&<aside className="diagram-inspector"><Field label="Diagram name"><input value={active.name} maxLength={100} onChange={(event)=>commit((diagram)=>({...diagram,name:event.target.value}),false)}/></Field>{selectedNode?<NodeInspector node={selectedNode} vlans={vlanOptions} update={updateNode}/>:selectedEdge?<LinkInspector link={selectedEdge} vlans={vlanOptions} update={updateLink}/>:<EmptyState title="Nothing selected">Select a device or link to edit its metadata.</EmptyState>}</aside>}
    </div>
  </>
}

function NodeInspector({node,vlans,update}:{node:DiagramNode;vlans:Array<{id:string;vlanId:number;name:string;planName:string}>;update:(patch:Partial<DiagramNode>)=>void}){return <div className="stack" style={{marginTop:16}}><span className="eyebrow">Selected device</span><Field label="Name"><input value={node.name} onChange={(event)=>update({name:event.target.value})}/></Field><Field label="Device type"><select value={node.type} onChange={(event)=>update({type:event.target.value as DeviceType})}>{nodeTypes.map((item)=><option value={item.type} key={item.type}>{item.label}</option>)}</select></Field><Field label="Management IP"><input className="mono" value={node.managementIp??''} onChange={(event)=>update({managementIp:event.target.value})}/></Field><Field label="Vendor / model"><input value={node.vendorModel??''} onChange={(event)=>update({vendorModel:event.target.value})}/></Field><Field label="Location"><input value={node.location??''} onChange={(event)=>update({location:event.target.value})}/></Field><Field label="Referenced VLAN"><select value={node.vlanId??''} onChange={(event)=>update({vlanId:event.target.value||undefined})}><option value="">No VLAN reference</option>{vlans.map((vlan)=><option value={vlan.id} key={vlan.id}>{vlan.planName} · {vlan.vlanId} {vlan.name}</option>)}</select></Field><Field label="Color"><input type="color" value={node.color??'#2387c9'} onChange={(event)=>update({color:event.target.value})}/></Field><Field label="Notes"><textarea value={node.notes??''} onChange={(event)=>update({notes:event.target.value})}/></Field></div>}
function LinkInspector({link,vlans,update}:{link:DiagramLink;vlans:Array<{id:string;vlanId:number;name:string;planName:string}>;update:(patch:Partial<DiagramLink>)=>void}){return <div className="stack" style={{marginTop:16}}><span className="eyebrow">Selected connection</span><div className="input-row"><Field label="Source interface"><input value={link.sourceLabel??''} onChange={(event)=>update({sourceLabel:event.target.value})}/></Field><Field label="Destination interface"><input value={link.targetLabel??''} onChange={(event)=>update({targetLabel:event.target.value})}/></Field></div><Field label="Link speed"><input value={link.speed??''} placeholder="10 Gbps" onChange={(event)=>update({speed:event.target.value})}/></Field><Field label="VLAN / trunk label"><input value={link.vlanLabel??''} onChange={(event)=>update({vlanLabel:event.target.value})}/></Field><Field label="Referenced VLAN"><select value={link.vlanId??''} onChange={(event)=>update({vlanId:event.target.value||undefined})}><option value="">No VLAN reference</option>{vlans.map((vlan)=><option value={vlan.id} key={vlan.id}>{vlan.planName} · {vlan.vlanId} {vlan.name}</option>)}</select></Field><Field label="Line style"><select value={link.lineStyle??'solid'} onChange={(event)=>update({lineStyle:event.target.value as DiagramLink['lineStyle']})}><option value="solid">Solid</option><option value="dashed">Dashed</option><option value="dotted">Dotted</option></select></Field><Field label="Color"><input type="color" value={link.color??'#66748a'} onChange={(event)=>update({color:event.target.value})}/></Field><Field label="Notes"><textarea value={link.notes??''} onChange={(event)=>update({notes:event.target.value})}/></Field></div>}
