import { useMemo, useState } from 'react'
import { BookOpen, Search, Star } from 'lucide-react'
import { REFERENCE_SOURCES, REFERENCE_VERSION, referenceEntries, searchReferences, type ReferenceKind } from '../data/reference'
import { useAppData } from '../state/DataContext'
import { EmptyState, Field, PageIntro } from '../components/UI'

const kinds: ReferenceKind[] = ['TCP','UDP','TCP/UDP','IP Protocol','EtherType','ICMP','ICMPv6']

export function ReferencePage() {
  const { data, setData, notify } = useAppData()
  const [query,setQuery] = useState('')
  const [kind,setKind] = useState<'all' | ReferenceKind>('all')
  const [favoritesOnly,setFavoritesOnly] = useState(false)
  const [view,setView] = useState<'reference'|'about'>('reference')
  const results = useMemo(() => searchReferences(query, kind === 'all' ? [] : kind === 'TCP' ? ['TCP','TCP/UDP'] : kind === 'UDP' ? ['UDP','TCP/UDP'] : [kind]).filter((entry) => !favoritesOnly || data.preferences.favoriteReferences.includes(entry.id)), [query,kind,favoritesOnly,data.preferences.favoriteReferences])
  const toggle = (id: string) => { const present = data.preferences.favoriteReferences.includes(id); setData((current) => ({ ...current, preferences: { ...current.preferences, favoriteReferences: present ? current.preferences.favoriteReferences.filter((item) => item !== id) : [...current.preferences.favoriteReferences,id] } })); notify(present ? 'Removed from favorites' : 'Added to favorites') }
  return <>
    <PageIntro eyebrow="Bundled data" title="Port & Protocol Reference" description="Search common transport services, IP protocols, EtherTypes, and ICMP types without an internet connection." actions={<div className="segmented"><button className={view === 'reference' ? 'active' : ''} onClick={() => setView('reference')}>Reference</button><button className={view === 'about' ? 'active' : ''} onClick={() => setView('about')}>Data sources</button></div>} />
    {view === 'about' ? <AboutSources /> : <section className="panel"><div className="panel-body"><div className="toolbar"><Field label="Search number, range, name, or description"><div className="search-field"><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Examples: 443, 160-180, BGP, routing…" /></div></Field><Field label="Entry type"><select value={kind} onChange={(event) => setKind(event.target.value as typeof kind)}><option value="all">All types</option>{kinds.map((item) => <option key={item}>{item}</option>)}</select></Field><label className="check-row" style={{ minHeight: 40 }}><input type="checkbox" checked={favoritesOnly} onChange={(event) => setFavoritesOnly(event.target.checked)} />Favorites only</label></div></div><div className="panel-footer">{results.length} of {referenceEntries.length} bundled entries · Dataset snapshot {REFERENCE_VERSION}</div>
      <div className="table-wrap">{results.length ? <table className="data-table"><thead><tr><th>Favorite</th><th>Number / range</th><th>Name</th><th>Type</th><th>Description</th><th>Category</th></tr></thead><tbody>{results.map((entry) => <tr key={entry.id}><td><button className="icon-button" onClick={() => toggle(entry.id)} aria-label={`${data.preferences.favoriteReferences.includes(entry.id) ? 'Remove' : 'Add'} ${entry.name} ${entry.number} ${data.preferences.favoriteReferences.includes(entry.id) ? 'from' : 'to'} favorites`}><Star fill={data.preferences.favoriteReferences.includes(entry.id) ? 'currentColor' : 'none'} /></button></td><td className="mono"><strong>{entry.number}</strong></td><td><strong>{entry.name}</strong></td><td><span className={`tag ${entry.kind.toLowerCase().includes('tcp') ? 'tcp' : entry.kind.toLowerCase().includes('udp') ? 'udp' : ''}`}>{entry.kind}</span></td><td>{entry.description}</td><td>{entry.category}</td></tr>)}</tbody></table> : <EmptyState icon={<BookOpen />} title="No matching reference entries" action={<button onClick={() => { setQuery(''); setKind('all'); setFavoritesOnly(false) }}>Clear search</button>}>Try an exact number, a number inside a bundled range, or a service description.</EmptyState>}</div></section>}
  </>
}

function AboutSources() {
  return <div className="grid two"><section className="panel"><div className="panel-header"><div><h2>Dataset provenance</h2><p>Version-controlled snapshot: {REFERENCE_VERSION}</p></div></div><div className="panel-body stack"><p style={{ color:'var(--muted)',fontSize:'.82rem',lineHeight:1.6 }}>The application contains a curated subset of facts from public IANA registries. Registry facts are maintained by IANA and are usable as factual reference data; descriptions in this project are concise original summaries. No data is fetched at runtime.</p>{REFERENCE_SOURCES.map((source) => <div className="notice" key={source.name}><strong>{source.name}</strong><br/><span className="mono" style={{fontSize:'.7rem'}}>{source.url}</span></div>)}</div></section><section className="panel"><div className="panel-header"><h2>Update procedure</h2></div><div className="panel-body"><ol style={{ color:'var(--muted)',fontSize:'.82rem',lineHeight:1.8,paddingLeft:20 }}><li>Review the current IANA registries at the URLs listed here.</li><li>Update the curated entries in <span className="mono">src/data/reference.ts</span>.</li><li>Preserve original concise descriptions and category tags.</li><li>Update the dataset snapshot date.</li><li>Run search tests, lint, and the production build.</li></ol><div className="notice warning">This is a practical common-entry reference, not a complete substitute for the authoritative live registries. Verify unusual or newly assigned values before production changes.</div></div></section></div>
}

